# Generated by Django 4.2.7 on 2023-11-24 20:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seven_class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='lesson_images/')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='lesson_files/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lesson_files/')),
                ('presentation', models.FileField(blank=True, null=True, upload_to='lesson_files/')),
                ('youtube_video_url', models.URLField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seven_class.object7')),
            ],
        ),
    ]
