# Generated by Django 4.2.7 on 2023-11-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_class', '0002_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
