# Generated by Django 4.2.7 on 2023-11-24 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seven_class', '0003_materialtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='material_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seven_class.materialtype'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
