# Generated by Django 4.2.7 on 2023-11-27 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seven_class', '0005_alter_lesson_material_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialType',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='material_type',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='seven_class.object7'),
        ),
    ]
