# Generated by Django 4.2.7 on 2023-11-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_class', '0007_alter_lesson_docx_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='google_form',
            field=models.URLField(blank=True, null=True),
        ),
    ]
