# Generated by Django 4.2.7 on 2023-11-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_class', '0008_lesson_google_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='object7',
            name='img_sub',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
