# Generated by Django 4.2.7 on 2023-11-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_class', '0009_object7_img_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Текс для читача'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='docx_file',
            field=models.URLField(blank=True, null=True, verbose_name='DOCX Файл'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='google_form',
            field=models.URLField(blank=True, null=True, verbose_name='Форма для тестів'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Картинка до уроку'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_files/', verbose_name='ПДФ Файл'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to='lesson_files/', verbose_name='Презентація'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Тема уроку'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='youtube_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Відео з YouTube'),
        ),
        migrations.AlterField(
            model_name='object7',
            name='img_sub',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Картинка для предмету'),
        ),
        migrations.AlterField(
            model_name='object7',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва предмету'),
        ),
    ]
