# Generated by Django 4.2.7 on 2023-11-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seven_class', '0010_alter_lesson_content_alter_lesson_docx_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='seven_class.object7', verbose_name='Уроки'),
        ),
    ]
