# Generated by Django 4.2.7 on 2023-11-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seven_class', '0012_alter_lesson_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object7',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предмети'},
        ),
    ]
